### ISSUE TITLE
Qutebrowser shows error message when creating a new window

### ISSUE THREAD

**Issue by minimaximalist** [lrustand/qutebrowser.el#14]
The error message reads:
> Errors occurred while reading config.py:
  Unhandled exception - ValueError: emacs is already registered!

And there is a traceback in the message log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/configfiles.py", line 989, in read_config_py
    exec(code, module.__dict__)
  File "/home/me/.config/qutebrowser/emacs_ipc.py", line 16, in <module>
    class EmacsIPCServer(IPCServer):
  File "/home/me/.config/qutebrowser/emacs_ipc.py", line 111, in EmacsIPCServer
    @cmdutils.register(instance="emacs-ipc", maxsplit=0, name="emacs")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/api/cmdutils.py", line 161, in __call__
    cmd.register()
  File "/usr/lib/python3.12/site-packages/qutebrowser/commands/command.py", line 554, in register
    raise ValueError("{} is already registered!".format(self.name))
ValueError: emacs is already registered!
```

**Comment by lrustand** [comment]
Yeah, it seems that if the python file is loaded again after the command is already defined it throws an error. This has happened to me too, but only if I have manually reloaded the python file with `:config-source`. Am I understanding you correct that this happens any time a new window is created?

Unfortunately I haven't yet found a way to allow the command to be redefined. However, this command is not in use at all, and was simply added in case it would be useful for end users. Since it causes more problems than it solves, I think I might just remove it for the time being, and suggest to use `:spawn emacsclient -e` instead of `:emacs`.

This is related to a bigger issue: it is currently not possible to cleanly reload the python backend. To mitigate that, I just make sure that if the backend is already initialized (i.e there is already a `EmacsIPCServer` and `EmacsHookManager` instance registered in `objreg`), then reloading the files does not try initializing it again. This is a problem, since the old implementation of the python code will be running until Qutebrowser is restarted. Meaning that if I push incompatible changes to the RPC implementation (which admittedly I have been doing rather frequently) things _will_ break.

**Comment by minimaximalist** [comment]
Yes, the error occurs whenever a new window is created. Commenting 
out the line mentioned in the traceback does resolve the issue, so 
removing the function should work.

**Comment by lrustand** [comment]
Closing this as I have disabled the command. I have also addressed the other issue I mentioned aboved, where the backend could not be reloaded/restarted. The IPC server and the hook manager should now replace themselves when their files are sourced.

Let me know if there are any more problems.
